version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: samraimispiderman1234moattehosikattanaanderewgafieldttekinaamaizing
      MYSQL_DATABASE: dumdumb_db
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dumdumb_network

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/data
    networks:
      - dumdumb_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - DATABASE_URL=mysql://root:samraimispiderman1234moattehosikattanaanderewgafieldttekinaamaizing@db:3306/dumdumb_db
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db
      - redis
    networks:
      - dumdumb_network

networks:
  dumdumb_network:
    driver: bridge

volumes:
  mysql_data:
  redis_data:
